// Generated by CoffeeScript 1.6.3
var intervalo = 0;

(function($, window) {
	var Plugin, document, nomePlugin, padroes;
	nomePlugin = "menu";
	document = window.document;
	padroes = {
	};
	Plugin = (function() {
		function Plugin(elemento, opcoes) {
			this.elemento = elemento;
			this.$elemento = $(this.elemento);
			this.opcoes = $.extend({}, padroes, opcoes);
			this.iniciar();
		}

		Plugin.prototype.iniciar = function() {
			var $elemento, opcoes, posicionarSubmenus;
			$elemento = this.$elemento;
			opcoes = this.opcoes;
			posicionarSubmenus = function() {
				$elemento.find(".agrupador").each(function() {
					var $agrupador, $unidade, larguraItens, posicaoAcaoEmRelacaoGrupo, posicaoSubmenu, quantidadeItens;
					$agrupador = $(this);
					$unidade = $agrupador.parents(".unidade");

					quantidadeItens = $agrupador.find(".itens").length;
					larguraItens = (quantidadeItens * $agrupador.find(".itens").eq(0).outerWidth()) + (quantidadeItens - 1);
					posicaoAcaoEmRelacaoGrupo = $unidade.find(".acao").offset().left - $elemento.find(".grupo").offset().left;
					posicaoSubmenu = posicaoAcaoEmRelacaoGrupo + larguraItens;

					$agrupador.css({
						left: -larguraItens/2 + $unidade.find(".acao").position().left +$unidade.outerWidth()/2,
						top: $unidade.parent().outerHeight() + 10,
						width: larguraItens
					});
				});
			};
			posicionarSubmenus();
			$(window).on("load", function() {
				return posicionarSubmenus();
			});
			$(window).on("resize", function() {
				return posicionarSubmenus();
			});
			$elemento.find(".acao, .agrupador").mouseenter(function() {
				var $unidade;
				$unidade = $(this).parents(".unidade");
				$unidade.next().addClass("proximo");
				$unidade.addClass("sobre").find(".agrupador").show();
			});
			$elemento.find(".acao, .agrupador").mouseleave(function() {
				var $unidade;
				$unidade = $(this).parents(".unidade");
				if (!$unidade.before().hasClass("selecionado")) {
					$unidade.next().removeClass("proximo");
				}
				$unidade.removeClass("sobre").find(".agrupador").hide();
			});

			return $elemento.find(".selecionado").next().addClass("proximo");
		};

		return Plugin;

	})();
	return $.fn[nomePlugin] = function(opcoes) {
		return this.each(function() {
			if (!$.data(this, "plugin_" + nomePlugin)) {
				return $.data(this, "plugin_" + nomePlugin, new Plugin(this, opcoes));
			}
		});
	};
})(jQuery, window);

$(function() {
	$(".cabecalho .menu").menu();
	$(".cabecalho .menu-area-logada").menu();
});


$(function(){   
	var nav = $('.cabecalho');   
	$(window).scroll(function () { 
		if ($(this).scrollTop() > 480) { 
			nav.addClass("fixar"); 
		} else { 
			nav.removeClass("fixar"); 
		} 
	});  
});